[package]
name = "xu-os"
version = "0.1.0"
authors = ["estraining <dylatos2022@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
